version: 2.1
orbs: 
  python: circleci/python@2.0.3
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: python --version
  test1:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: python --version
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - hold: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test2 has succeeded
           - build
      # On approval of the `hold` job, any successive job that requires the `hold` job will run.
      # In this case, a user is manually triggering the deploy job.
      - test1:
          requires:
            - hold