version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.6.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
  test:
    steps:
      - checkout
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: pytest --version
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build